name: clothe_closet_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
  
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.6.2
  image_picker: ^1.0.4
  firebase_core: ^2.32.0
  http: ^0.13.5
  path_provider: ^2.1.2
  model_viewer_plus: ^1.9.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/closet_logo.png