// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQFf1-hDobm6AoT7RLzsSx5sVFO2aN2DY',
    appId: '1:65847183555:web:f77a7a0bed0934633a3a76',
    messagingSenderId: '65847183555',
    projectId: 'clothe-closet-app',
    authDomain: 'clothe-closet-app.firebaseapp.com',
    storageBucket: 'clothe-closet-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-R74BRYe-BEs0mqu8Ccvvq3N1xrE-ggM',
    appId: '1:65847183555:android:11e67bda98e612c13a3a76',
    messagingSenderId: '65847183555',
    projectId: 'clothe-closet-app',
    storageBucket: 'clothe-closet-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArjM1kxIJmMlyljlIRwERfvK9ewxEP3SM',
    appId: '1:65847183555:ios:f68cab459cf3124c3a3a76',
    messagingSenderId: '65847183555',
    projectId: 'clothe-closet-app',
    storageBucket: 'clothe-closet-app.firebasestorage.app',
    iosBundleId: 'com.example.clotheClosetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArjM1kxIJmMlyljlIRwERfvK9ewxEP3SM',
    appId: '1:65847183555:ios:f68cab459cf3124c3a3a76',
    messagingSenderId: '65847183555',
    projectId: 'clothe-closet-app',
    storageBucket: 'clothe-closet-app.firebasestorage.app',
    iosBundleId: 'com.example.clotheClosetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQFf1-hDobm6AoT7RLzsSx5sVFO2aN2DY',
    appId: '1:65847183555:web:312c8f0206bca9f43a3a76',
    messagingSenderId: '65847183555',
    projectId: 'clothe-closet-app',
    authDomain: 'clothe-closet-app.firebaseapp.com',
    storageBucket: 'clothe-closet-app.firebasestorage.app',
  );

}